# generate main config script
Log "Generating programs configuration"
printf "# [Autogenerated - do not edit: at $(date)] CLI-Config Install configuration --------" > $CLI_CONFIG_PROGRAMS_CONF
echo >> $CLI_CONFIG_PROGRAMS_CONF

echo '# init all cli-config tools' >> $CLI_CONFIG_PROGRAMS_CONF
echo 'autoload -Uz compinit && compinit' >> $CLI_CONFIG_PROGRAMS_CONF

# plugin manager must be sourced first so lazyload is available to other confs
PLUGIN_MANAGER="${CLI_CONFIG_MODULES:-zimfw}"
PLUGIN_MANAGER_CONF=$(find $CLI_CONFIG_CONF_LOCATION -type f -name "${PLUGIN_MANAGER}.conf.*" | head -1)
[[ -n "$PLUGIN_MANAGER_CONF" ]] && echo ". $PLUGIN_MANAGER_CONF" >> $CLI_CONFIG_PROGRAMS_CONF

for tool in $(find  $CLI_CONFIG_CONF_LOCATION  -type f \( -name '*.conf.sh' -o -name '*.conf.zsh' \) -not -name "${PLUGIN_MANAGER}.conf.*" | sort); do
  echo ". $tool" >> $CLI_CONFIG_PROGRAMS_CONF
done

echo eval "\$(thefuck --alias)" >> $CLI_CONFIG_PROGRAMS_CONF

