# generate main config script
Log "Generating programs configuration"
printf "# [Autogenerated - do not edit: at $(date)] CLI-Config Install configuration --------" >$CLI_CONFIG_PROGRAMS_CONF
echo >>$CLI_CONFIG_PROGRAMS_CONF

echo '# init all cli-config tools' >>$CLI_CONFIG_PROGRAMS_CONF
{
  echo 'autoload -Uz compinit'
  echo '# Glob qualifiers need EXTENDED_GLOB. Remember the prior state and restore it,'
  echo '# rather than unconditionally clearing an option the user may rely on.'
  echo '_cli_config_eg=0; [[ -o extendedglob ]] || { _cli_config_eg=1; setopt extendedglob }'
  echo '_cli_config_zcompdump=${ZDOTDIR:-$HOME}/.zcompdump'
  echo '# The previous [[ -n path(#qN.mh+24) ]] form took the -C branch when the dump was'
  echo '# MISSING as well as when it was fresh, so a first run (or a deleted dump) loaded'
  echo '# no completions at all. Match through an array instead: (#qN.mh-24) yields the'
  echo '# dump only if it exists, is a plain file, and is less than 24h old.'
  echo '_cli_config_zcompdump_fresh=( ${_cli_config_zcompdump}(#qN.mh-24) )'
  echo 'if (( $#_cli_config_zcompdump_fresh )); then'
  echo '  compinit -C -d ${_cli_config_zcompdump}'
  echo 'else'
  echo '  compinit -d ${_cli_config_zcompdump}'
  echo '  # compinit only rewrites the dump when completions actually changed, so its'
  echo '  # mtime can stay stale forever - touch it so the 24h check resets and the'
  echo '  # next start takes the fast -C path.'
  echo '  touch ${_cli_config_zcompdump}'
  echo 'fi'
  echo '(( _cli_config_eg )) && unsetopt extendedglob'
  echo 'unset _cli_config_zcompdump _cli_config_zcompdump_fresh _cli_config_eg'
} >>$CLI_CONFIG_PROGRAMS_CONF

# plugin manager must be sourced first so lazyload is available to other confs
PLUGIN_MANAGER="${CLI_CONFIG_MODULES:-zimfw}"
PLUGIN_MANAGER_CONF=$(find $CLI_CONFIG_CONF_LOCATION -type f -name "${PLUGIN_MANAGER}.conf.*" | head -1)
[[ -n "$PLUGIN_MANAGER_CONF" ]] && echo ". $PLUGIN_MANAGER_CONF" >>$CLI_CONFIG_PROGRAMS_CONF

for tool in $(find $CLI_CONFIG_CONF_LOCATION -type f \( -name '*.conf.sh' -o -name '*.conf.zsh' \) -not -name "${PLUGIN_MANAGER}.conf.*" | sort); do
  echo ". $tool" >>$CLI_CONFIG_PROGRAMS_CONF
done

# `thefuck --alias` costs ~370ms per shell start (python interpreter startup), which
# was roughly half of total startup time. Define a stub that pays that cost only on
# the first `fuck` invocation, then replaces itself with the real alias function.
{
  echo 'fuck() {'
  echo '  unset -f fuck'
  echo '  eval "$(thefuck --alias)"'
  echo '  fuck "$@"'
  echo '}'
} >>$CLI_CONFIG_PROGRAMS_CONF
