# generate main config script
Log "Generating programs configuration"
printf "# [Autogenerated - do not edit: at $(date)] CLI-Config Install configuration --------" >$CLI_CONFIG_PROGRAMS_CONF
echo >>$CLI_CONFIG_PROGRAMS_CONF

echo '# init all cli-config tools' >> $CLI_CONFIG_PROGRAMS_CONF
{
  echo 'autoload -Uz compinit'
  echo 'setopt extendedglob'
  echo '_cli_config_zcompdump=${ZDOTDIR:-$HOME}/.zcompdump'
  echo 'if [[ -n ${_cli_config_zcompdump}(#qN.mh+24) ]]; then'
  echo '  compinit'
  echo '  # compinit only rewrites the dump when completions actually changed, so its'
  echo '  # mtime can stay stale forever - touch it so the 24h check resets and the'
  echo '  # next start takes the fast -C path.'
  echo '  touch ${_cli_config_zcompdump}'
  echo 'else'
  echo '  compinit -C'
  echo 'fi'
  echo 'unset _cli_config_zcompdump'
  echo 'unsetopt extendedglob'
} >> $CLI_CONFIG_PROGRAMS_CONF

# plugin manager must be sourced first so lazyload is available to other confs
PLUGIN_MANAGER="${CLI_CONFIG_MODULES:-zimfw}"
PLUGIN_MANAGER_CONF=$(find $CLI_CONFIG_CONF_LOCATION -type f -name "${PLUGIN_MANAGER}.conf.*" | head -1)
[[ -n "$PLUGIN_MANAGER_CONF" ]] && echo ". $PLUGIN_MANAGER_CONF" >>$CLI_CONFIG_PROGRAMS_CONF

for tool in $(find $CLI_CONFIG_CONF_LOCATION -type f \( -name '*.conf.sh' -o -name '*.conf.zsh' \) -not -name "${PLUGIN_MANAGER}.conf.*" | sort); do
  echo ". $tool" >>$CLI_CONFIG_PROGRAMS_CONF
done

# `thefuck --alias` costs ~370ms per shell start (python interpreter startup), which
# was roughly half of total startup time. Define a stub that pays that cost only on
# the first `fuck` invocation, then replaces itself with the real alias function.
{
  echo 'fuck() {'
  echo '  unset -f fuck'
  echo '  eval "$(thefuck --alias)"'
  echo '  fuck "$@"'
  echo '}'
} >>$CLI_CONFIG_PROGRAMS_CONF
